Expectation Over Transformation Wrapper
bethgelab/foolbox pull request #719
Opened 2024-02-26 13:19 UTC by SerezD

Closes #191

My approach for implementing [EoT](https://arxiv.org/pdf/1707.07397.pdf). 
I tried to follow the suggestions of @zimmerrol. 

Basically, I created a new ExpectationOverTransformation Wrapper class that computes the forward pass `n_steps` times (default to 16) and returns the average prediction. 

I also created a new example for pytorch `resnet-18` model, which seems to work. 

**Potential Issue:** since the forward pass is executed `n_steps` times, the attack takes a long time for execution.

2024-02-26 15:13 UTC, SerezD commented
By looking at the other test files, I have added some tests to assert that wrapping the model with EoT does not change clean / robust accuracy (when no random transforms are applied). Don't know if this is correct.

Also, I am not really sure how to add more complex tests (with random transformations applied to the input).

2024-03-01 13:39 UTC, zimmerrol requested changes
Except a few smaller things, this looks good to me!

2024-03-01 13:39 UTC, zimmerrol commented on tests/test_eot_attack.py
Let's rename this file to something like `test_eot_wrapper.py`.

2024-03-01 13:39 UTC, zimmerrol commented on tests/test_eot_attack.py
> +def test_eot_attack(
See comment above.

2024-03-01 13:39 UTC, zimmerrol commented on tests/test_eot_attack.py
> +
Remove unnecessary whitespace.

2024-03-01 16:17 UTC, SerezD commented
I have uploaded a refactored version, which should now be compatible with `black` and `mypy` requirements. This should fix the failed checks for the Tests part.

2024-03-03 08:26 UTC, zimmerrol requested changes
Only one minor comment left, then we can merge this!

2024-03-03 08:26 UTC, zimmerrol commented on foolbox/models/wrappers.py
> +class ExpectationOverTransformationWrapper(Model):
Sorry for not mentioning this earlier, but can you please add docstrings to the class & module like its done for the other classes in the project?

2024-03-04 08:50 UTC, zimmerrol approved these changes

2024-03-04 09:18 UTC, merged